"""
run_all.py -- run every entroptics validation experiment and (re)write RESULTS.md.

Deterministic: every experiment is seeded, so RESULTS.md is byte-reproducible.
    python run_all.py            # run all, rewrite RESULTS.md

Each experiment module exposes run() -> dict(title, setup, table, headline,
conclusion, metrics, [provisional]).  This driver only formats; the numbers are
produced by the experiment modules and their common.py generators.
"""
from __future__ import annotations

import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import exp1_correlation_length as e1
import exp2_dmd_recovery as e2
import exp3_planted_modes as e3
import exp4_coherence as e4
import exp5_mercer_stationarity as e5
import exp6_etendue_sbw as e6
import miller_madow_check as mm

MODULES = [e1, e2, e3, e4, e5, e6, mm]

INTRO = """# Entroptics -- empirical validation

Quantitative ground-truth evidence for the reads in the entroptics paper.  Each
experiment **plants a KNOWN ground truth** (a correlation length, a linear operator's
eigenvalues, a mode count, ordered vs permuted structure, stationary vs regime-switch,
a rank/bandwidth) and shows the corresponding read **recovers it**.  Everything is
seeded and deterministic; regenerate with `python research/validation/run_all.py`.

Library version read under test: entroptics 0.1.0 (numpy backend).  Scripts:
`common.py` (seeded ground-truth generators), `exp1..exp6_*.py`, `miller_madow_check.py`.
"""


def main():
    t0 = time.time()
    results = [m.run() for m in MODULES]

    lines = [INTRO, "\n## Headline numbers\n"]
    for r in results:
        tag = " *(provisional; see note)*" if r.get("provisional") else ""
        lines.append(f"- **{r['title']}**{tag} -- {r['headline']}")

    lines.append("\n---\n")
    for r in results:
        lines.append(f"\n## {r['title']}\n")
        lines.append(f"**Setup.** {r['setup']}\n")
        lines.append(r["table"])
        lines.append(f"\n**Conclusion.** {r['conclusion']}\n")

    lines.append("\n---\n")
    lines.append(f"_Generated by run_all.py in {time.time() - t0:.1f}s; "
                 f"deterministic (fixed seeds)._\n")

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "RESULTS.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} ({time.time() - t0:.1f}s)")


if __name__ == "__main__":
    main()
